### ISSUE TITLE
Is it Watchbot or WatchBot?

### ISSUE THREAD

**Issue by infojunkie** [meedan/watchbot#2]
I prefer Watchbot, but let's discuss :-)

**Comment by TomElRumi** [comment]
I also prefer Watchbot, and it aligns with our decision to go w/ Checkdesk
and not CheckDesk :)

On 20 April 2015 at 11:29, Karim Ratib <notifications@github.com> wrote:

> I prefer Watchbot, but let's discuss :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meedan/watchbot/issues/2>.
>



-- 
Tom Trewinnard  |  +1 520 891 6171  |  @tom_el_rumi
<http://twitter.com/tom_el_rumi>  |  skype. tom.trewinnard  |
http://meedan.org  |  http://checkdesk.org |  http://meedanlabs.com

recent coverage in Columbia Journalism Review
<http://www.cjr.org/behind_the_news/bellingcat_brown_moses.php>
please note new email tom@meedan.com

**Comment by caiosba** [comment]
Tom gave a killer argument, so I changed it to Watchbot :)
